### PR TITLE
Ef/slight reorg

### PR DESCRIPTION
**Pull request by emilyfeder**
I wanted to make our app a little more modular in preparation for us each working in our own areas, so I read the tutorial on how to structure an application here: http://flask.pocoo.org/docs/1.0/tutorial/factory/

I also separated out the renxt client into its own module to make things a little cleaner and to make it easier to re-use endpoints.
The geocoding client could be its own module as well.

My next step would be to write and test the endpoint to update the coordinates field in the constituent record.

### CODE REVIEW

**Comment by Noleli** [comment]
Awesome, thanks Emily! I’ve also been looking into what it would take to update the coordinates field. Unfortunately, it doesn’t seem like there’s a way to query for only those constituents who don’t have a coordinates value, nor is there a way to query for constituents whose coordinates value was updated before a certain datetime.

I did get as far as identifying the endpoint to get custom field values. It’s called “Constituent custom field list (All constituents)”.

**Comment by alexsoble** [comment]
@emilyfeder Hey Emily! I think separating out the RENext client into its own class is a really good idea: way more modular that way. Same with the geocoder. 

I can't speak to the specifics of the implementation in this PR because I haven't ready the Flask doc you shared yet, but I'd bet this is spot on. Reading the docs now! 

@Noleli Arrrrgh what a bummer that there's no way to query for constituents who have a particular value for a particular field! That seems so elementary!

**Comment by alexsoble** [comment]
P.S. @emilyfeder I saw you requested my review on these changes and I took a couple of days to get back to you. Don't let my review/lack of review hold you up on a PR: sometimes I get busy and can't respond in a timely way. Want to make sure I'm not blocking your progress! If you @-ping me about major changes, that's great, otherwise I'll see your work when I `git pull`. 

One exception might be a PR that you aren't sure about in terms of security/privacy implications.

**Comment by emilyfeder** [comment]
Thanks! I should have merged a few days ago, sorry for the delay.

**Pull request merged**
