### PR TITLE
Heroku deploy

### PR DESCRIPTION
**Pull request by alexsoble**
# What's new

Hey there @emilyfeder & @Noleli — these are changes I found that I had to make to get the app to deploy nicely on Heroku. Do these seem reasonable?

Not 100% sure how `environment.yml` and `requirements.txt` interact, but Heroku only accepts `requirements.txt`.

### CODE REVIEW

**Comment by emilyfeder** [comment]
I think that looks good!

**Comment by emilyfeder** [comment]
Actually, perhaps you want to add a section to the readme about the heroku deploy process -- why requirements.txt is added, and the link to the heroku app.

**Comment by alexsoble** [comment]
@emilyfeder Good call!

**Comment by alexsoble** [comment]
@emilyfeder Added Deployment section to README.md

**Comment by alexsoble** [comment]
Merging this in as a selfie 👍

**Pull request merged**
