### PR TITLE
Handle application config in code

### PR DESCRIPTION
**Pull request by alexsoble**
# Notes 

+ This allows us to set default config settings based on the app environment (development, production, test)
  + Removes the need to manually export every variable in development 
  + Sets us up for a test suite which we can configure with default variables for the `test` environment 
+ Switch over to a `development_config.py` file, easier to edit and update than using `export` in the command line
+ New command to start the app: `APP_ENV=development flask run`

### CODE REVIEW

**Comment by alexsoble** [comment]
This is ready for review or comments @emilyfeder and/or @Noleli! I've tested out the `development_config.py` workflow and was able to verify that it populates config correctly, here's what I get when I add nonsense config to `development_config.py` and run the app:

screen shot 2018-08-08 at 6 40 38 pm

**Comment by alexsoble** [comment]
Note: set `APP_ENV=production` in Heroku before or immediately after deploying.

**Comment by alexsoble** [comment]
I'm going to 🚢 this one as a selfie because it will make it easier for me to test out #7 and ship. Feel free to add comments/make changes after the fact, all code is reversible and editable. 👍

**Comment by emilyfeder** [comment]
looks great, thanks!

**Pull request merged**
