### PR TITLE
Add script to run app locally

### PR DESCRIPTION
**Pull request by alexsoble**
Start app:

```
$ ./start_app.sh
```

### CODE REVIEW

**Comment by emilyfeder** [comment]
Does this work if you run it, then ctrl^C and then run it again?

**Comment by alexsoble** [comment]
@emilyfeder Yes, it works for me when you do that. Does it work for you?

**Comment by emilyfeder** [comment]
I hadn't tried it out but was curious. Glad to know it works for you!

**Comment by alexsoble** [comment]
👍 👍  I'll 🚢 and we can improve it from here!

**Pull request merged**
